# -*- coding: utf-8 -*-
"""DAY 2 ASSIGNMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12j937eFXFMlxaIVZCQ5fBKvUTafm0ucK
"""

#DAY 2 ASSIGNMENT
#GAURAV CHAUDHARI

import numpy as np

List1 = [1,2,3,4,5]
List2 = [2,3,4,5,6]
List3 = [4,5,6,7,8]

arr1 = np.array([List1,List2,List3])
arr1

arr1[1:3,1:3]

